imusic/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    path('',include('myalbums.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('allauth.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Use static() to add url mapping to serve static files during development (only)


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

myalbums/urls.py
from django.urls import path, include
from . import views
from .views import *
from django.conf import settings

from django.views.generic import RedirectView
from django.conf.urls import url

urlpatterns = [
    path('',index, name='index'),
    path('category/', CategoryListView.as_view(), name='category'),
    path('category/<int:pk>', CategoryDetailView.as_view(), name='category-detail'),
    path('song/', SongListView.as_view(), name='song'),
    path('song/<int:pk>', views.favorite, name='song-detail'),
    path('song/<int:pk>/lyric/', views.addlyric, name='lyric'),
    path('song/upload', SongUploadView.as_view(), name='upload'),
    path('artist/', ArtistListView.as_view(), name='artist'),
    path('artist/<int:pk>', ArtistDetailView.as_view(), name='artist-detail'),
    path('profile', views.profile, name ='profile'),
    path('hotsong/', HotSongListView.as_view(), name='hot-song'),
    path('register/', register, name='register'),
    path('search-song/', SearchSongListView.as_view(), name='search'),
    path('station/', StationListView.as_view(), name='user-list'),
    path('station/<int:pk>', views.follow, name='follow'),
    path('favorite/', views.FavoriteListView.as_view(), name='favorite'),
    path('review/<int:pk>/create', ReviewAdd, name='review_create'),
    path('history/', views.ActivityListView.as_view(), name='history'),
    path('comment/<int:pk>/create', CommentAdd , name='AddComment'),
    path('activate/<uidb64>/<token>', activate, name='activate'),
    url(r'^favicon\.ico$',RedirectView.as_view(url='/static/images/favicon.ico')),
	# path(r'^delete/(?P<notification_id>\d+)/$', name='delete_notification'),
	path('show/', views.show_notification, name='show_notification'),
]

myalbums/models.py
from django.db import models
from django.db.models.functions import math
from django.dispatch import receiver
from django.shortcuts import render
from django.urls import reverse
from datetime import datetime
from django.utils import timezone
from django.contrib.auth import get_user_model
import numpy as np
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser
)
from time import strftime, gmtime
from PIL import Image
from django.db.models.signals import post_save
from django.conf import settings


class MyModelName(models.Model):
    """A typical class defining a model, derived from the Model class."""

    # Fields
    my_field_name = models.CharField(
        max_length=20, help_text='Enter field documentation')
    

    # Metadata
    class Meta:
        ordering = ['-my_field_name']

    # Methods
    def get_absolute_url(self):
        """Returns the url to access a particular instance of MyModelName."""
        return reverse('model-detail-view', args=[str(self.id)])

    def __str__(self):
        """String for representing the MyModelName object (in Admin site etc.)."""
        return self.my_field_name


class Category(models.Model):
    name_category = models.CharField(max_length=20, null=True, help_text=(
        'Enter a song category (e.g. Sad love)'))
    thumbnail = models.ImageField(upload_to="thumbnails", blank=False, default="default.jpeg")

    def get_absolute_url(self):
        return reverse('category-detail', args=[str(self.id)])

    def __str__(self):
        return self.name_category
    thumbnail = models.ImageField(upload_to="genres", default="default.jpeg")


class Album(models.Model):
    name_album = models.CharField(max_length=50)

    def get_absolute_url(self):
        return reverse('album-detail', args=[str(self.id)])

    def __str__(self):
        return self.name_album


class Lyric(models.Model):
    content = models.CharField(max_length=1000, null=True)
    song = models.ForeignKey('Song', on_delete=models.CASCADE)
    user = models.ForeignKey('User', on_delete=models.CASCADE)
    lyric_status = models.BooleanField(default=False)

    def __str__(self):
        return self.content


class Song(models.Model):
    title = models.CharField(max_length=200)
    artist = models.ManyToManyField(
        'Artist', help_text='Select song for this artist')
    category = models.ForeignKey(
        'Category', on_delete=models.SET_NULL, null=True)
    album = models.ManyToManyField(
        'Album', help_text='Select album for this song')
    hot = models.BooleanField(default=False)
    thumbnail = models.ImageField(upload_to="thumbnails", blank=False, default="default.jpg")
    song = models.FileField(upload_to="song_directory_path", default="default.mp3")
    playtime = models.CharField(max_length=10, default="0.00")
    size = models.IntegerField(default=0)

    @property
    def duration(self):
        return str(strftime('%H:%M:%S', gmtime(float(self.playtime))))

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('song-detail', args=[str(self.id)])

    def display_category(self):
        return ', '.join(category.name for category in self.category.all()[:5])

    def average_rating(self):
        all_ratings = map(lambda x: x.rating, self.review_set.all())
        return np.mean(list(all_ratings))

    def get_lyric(self):
         return Lyric.objects.filter(song=self)

class Artist(models.Model):
    name_artist = models.CharField(max_length=50)
    birthday = models.DateField(null=True, blank=True)
    biography = models.CharField(max_length=400, null=True, help_text=(
        'Enter your biography '))
    def get_absolute_url(self):
        return reverse('artist-detail', args=[str(self.id)])

    def __str__(self):
        return self.name_artist

    @property
    def file_size(self):
        if self.size == 0:
            return "0B"
        size_name = ("B", "KB", "MB", "GB", "TB", "PB", "EB", "ZB", "YB")
        i = int(math.floor(math.log(self.size, 1024)))
        p = math.pow(1024, i)
        s = round(self.size / p, 2)
        return "%s %s" % (s, size_name[i])


class UserManager(BaseUserManager):
    def create_user(self, email, password=None):
        """
        Creates and saves a User with the given email and password.
        """
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email),
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_staffuser(self, email, password):
        """
        Creates and saves a staff user with the given email and password.
        """
        user = self.create_user(
            email,
            password=password,
        )
        user.staff = True
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password):
        """
        Creates and saves a superuser with the given email and password.
        """
        user = self.create_user(
            email,
            password=password,
        )
        user.staff = True
        user.admin = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser):
    username = models.CharField(max_length=20)
    password = models.CharField(None, max_length=128)

    email = models.EmailField(
        verbose_name='email address', max_length=255, unique=True)
    active = models.BooleanField(default=True)
    staff = models.BooleanField(default=False)  # a admin user; non super-user
    admin = models.BooleanField(default=False)  # a superuser
    # notice the absence of a "Password field", that is built in.
    objects = UserManager()
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []  # Email & Password are required by default# .

    def __str__(self):
        return self.username

    def get_full_name(self):
        # The user is identified by their email address
        return self.email

    def get_short_name(self):
        # The user is identified by their email address
        return self.email

    def __str__(self):              # __unicode__ on Python 2
        return self.email

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        return self.staff

    @property
    def is_admin(self):
        "Is the user a admin member?"
        return self.admin

    @property
    def is_active(self):
        "Is the user active?"
        return self.active

    def get_followers(self):
        return Follow.objects.filter(following=self).count()

    def get_followings(self):
        return Follow.objects.filter(follower=self).count()

    def list_follower(self):
        followers = Follow.objects.filter(following=self)
        users = list()
        for follower in followers:
            users.append(User.objects.get(email=follower.follower))
        return users

    def list_following(self):
        followings = Follow.objects.filter(follower=self)
        users = list()
        for following in followings:
            users.append(User.objects.get(email=following.following))
        return users

    def list_favorite(self):
         user_favorite = Favorite.objects.filter(user_favorite=self)
         songs = list()
         for song in user_favorite:
            songs.append(Song.objects.get(title=song.song_favorite))
         return songs


class Comment(models.Model):
    review = models.ForeignKey('Review', on_delete=models.CASCADE)
    text = models.TextField()
    date_comment = models.DateTimeField(default=timezone.now)
    user = models.ForeignKey('User', on_delete=models.CASCADE)


class Review(models.Model):
    content_review = models.CharField(max_length=1000)
    song_review = models.ForeignKey('Song', on_delete=models.CASCADE)
    user_review = models.ForeignKey('User', on_delete=models.CASCADE)
    date_review = models.DateTimeField(default=timezone.now)
    RATING_CHOICES = (
        (1, '★'),
        (2, '★★'),
        (3, '★★★'),
        (4, '★★★★'),
        (5, '★★★★★'),
    )
    rating = models.IntegerField(choices=RATING_CHOICES)

    def __str__(self):
        return self.content_review

    @property
    def actual_rating(self):
        list_of_stars = []
        for star in range(self.rating):
            list_of_stars.append(star)
        return list_of_stars

    @property
    def hidden_rating(self):
        list_of_stars = []
        for star in range(5 - self.rating):
            list_of_stars.append(star)
        return list_of_stars


class Follow(models.Model):
    follower = models.ForeignKey(User, related_name='following', on_delete=models.CASCADE)
    following = models.ForeignKey(User, related_name='followers', on_delete=models.CASCADE)
    date_added = models.DateTimeField(default=datetime.now)

    class Meta:
        unique_together = ('follower', 'following')

    def __unicode__(self):
        return u'%s follows %s' % (self.follower, self.following)

class Favorite(models.Model):
    favorite_name = models.CharField(max_length=50)
    user_favorite = models.ForeignKey('User',related_name='user_favorite', on_delete=models.CASCADE)
    song_favorite = models.ForeignKey('Song', related_name='song_favorite',on_delete=models.CASCADE)

    class Meta:
        unique_together = ('user_favorite', 'song_favorite')

    def __unicode__(self):
        return u'%s follows %s' % (self.user_favorite, self.song_favorite)

class Profile (models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

myalbums/forms.py
from django import forms
from .models import User, Profile, Lyric, Review, Song , Comment
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django.contrib.auth.forms import UserCreationForm

class UserUpdateForm (forms.ModelForm):
    email = forms.EmailField()
    class Meta:
        model = User
        fields = ['username','email']

class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']

class RegisterForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirm password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username','email','password','password2')

    # def clean_email(self):
    #     email = self.cleaned_data.get('email')
    #     qs = User.objects.filter(email=email)
    #     if qs.exists():
    #         raise forms.ValidationError("email is taken")
    #     return email

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super(RegisterForm, self).save(commit=False)
        if commit:
            user.save()
        return user

class UserAdminCreationForm(forms.ModelForm):
    """
    A form for creating new users. Includes all the required
    fields, plus a repeated password.
    """
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('email',)

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super(UserAdminCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class UserAdminChangeForm(forms.ModelForm):
    """A form for updating users. Includes all the fields on
    the user, but replaces the password field with admin's
    password hash display field.
    """
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = User
        fields = ('email', 'password', 'active', 'admin')

    def clean_password(self):
        # Regardless of what the user provides, return the initial value.
        # This is done here, rather than on the field, because the
        # field does not have access to the initial value
        return self.initial["password"]

class LyricAddForm(forms.ModelForm):
    class Meta:
        model = Lyric
        fields = ['user', 'song', 'content']

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = '__all__'

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']

class SongUploadForm(forms.ModelForm):
    class Meta:
        model = Song
        fields = ("title", "category", "thumbnail", "song",)

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super(SongUploadForm, self).__init__(*args, **kwargs)

    def clean_user(self):
        return self.user

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']

myalbums/templates/myalbums/activity_list.html
{% extends 'layouts/base_generic.html' %}
{% load i18n  %}
{% load static %}

{% block content %}

    <main id="pageWrapper">

        <div class="banner bg-home"></div>
        <div class="main-container">

            <h1>History</h1>
            <h5>Where you can see your and following's activity</h5>
            <hr>
            <br> </br>
            <br> </br>

         <div class="row">
                  <div class="col-sm-9 col-md-6 ">
                  <h5 class="card-title mb-0">Your Follower: </h5>
                  <hr>
                      <br></br>
                  {% for activity in activity_list reversed %}
                  {% for activity_user in activity.user.list_follower %}
                      <div class="d-flex flex-wrap align-items-end">
                        <img  class="circular--landscape" src="{{ activity.user.profile.image.url }}" style="width: 50px; height: 50px">
                        <div class="col-xl-3 col-lg-3 col-sm-3"><h4><a href="{{ activity.user.profile.get_absolute_url }}" >{{ activity.user.username}}</a></h4>
                       </div>
                        <div class="col-xl-6 "><h5>{{ activity.activity }}</h5></div>
                        <div class="col-xl-5 "><p>{{ activity.datetime }}</p></div>
                     </div>
                    <hr>
                   {% endfor %}
                   {% endfor %}
                  </div>
                    <div class="col-sm-9 col-md-6 ">
                    <h5 class="card-title mb-0">You: </h5>
                    <hr>
                      <br></br>
                   {% for activity in activity_list reversed %}
                   {% if activity.user == request.user %}
                        <div class="d-flex flex-wrap align-items-end">
                        <img  class="circular--landscape" src="{{ activity.user.profile.image.url }}" style="width: 50px; height: 50px">
                        <div class="col-xl-3 col-lg-3 col-sm-3"><h4><a href="{{ activity.user.profile.get_absolute_url }}" > you </a></h4>
                       </div>
                        <div class="col-xl-6 "><h5>{{ activity.activity }}</h5></div>
                        <div class="col-xl-5 "><p>{{ activity.datetime }}</p></div>
                     </div>
                    <hr>
                    {% endif %}
                   {% endfor %}
                    </div>
         </div>
        </div>
        {% include 'includes/footer.html' %}

    </main>

{% endblock %}

myalbums/templates/myalbums/artist_detail.html
{% extends '../layouts/base_generic.html' %}
{% load static %}

{% block content %}

    <main id="pageWrapper">
        <div class="banner bg-artists"></div>
        <div class="main-container">
            <div class="row section text-center text-md-left">
                <div class="col-xl-3 col-lg-4 col-sm-5">
                    <img src="{% static 'images/artists/default.jpg' %}" alt="" class="card-img--radius-lg" style="filter: blur(4px) brightness(.9)">
                </div>
                <div class="col-xl-9 col-lg-8 col-sm-7">
                    <div class="row pt-4">
                        <div class="col-xl-8 col-lg-6">
                            <h5>{{ artist.name_artist }}</h5>
                            <p>DOB: --</p>
                            <div class="text-warning stars"><i class="la la-star"></i> <i class="la la-star"></i> <i class="la la-star"></i> <i class="la la-star"></i> <i class="la la-star-half-empty"></i></div>
                            <div class="mt-4"><a href="javascript:void(0);" class="btn btn-pill btn-air btn-bold btn-danger">Play All</a></div>
                        </div>
                        <div class="col-xl-4 col-lg-6">
                            <div class="pt-3 pt-lg-0 text-lg-right">
                                <button class="btn btn-pill btn-air btn-danger btn-icon-only"><i class="la la-heart-o"></i></button>
                                <button class="btn btn-pill btn-air btn-brand btn-icon-only"><i class="la la-share-alt"></i></button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="section">
                <ul class="nav nav-tabs line-tabs line-tabs-primary text-uppercase mb-4" id="artistDetails" role="tablist">
                    <li class="nav-item"><a class="nav-link active" id="song-tab" data-toggle="tab" href="#song" role="tab" aria-controls="song" aria-selected="true">Top Songs</a></li>
                    <li class="nav-item"><a class="nav-link" id="bio-tab" data-toggle="tab" href="#bio" role="tab" aria-controls="bio" aria-selected="false">Biography</a></li>
                </ul>
                <div class="tab-content" id="artistDetailsContent">
                    <div class="tab-pane fade show active" id="song" role="tabpanel" aria-labelledby="song-tab">
                        <div class="row align-items-end"><span class="col-6 font-weight-bold">{{ artist.song_set.all.count }} Track</span>
                            <div class="col-6 ml-auto">
                                <form action="#" class="form-inline justify-content-end">
                                    <label class="mr-2" for="filter1">Sorted By:</label>
                                    <select class="custom-select mr-sm-2" id="filter1">
                                        <option selected="selected">Popular</option>
                                        <option value="1">A-Z</option>
                                        <option value="2">Z-A</option>
                                    </select>
                                </form>
                            </div>
                            <div class="col-12">
                                <hr>
                            </div>
                        </div>
                        <div class="custom-list">
                            {% for song in artist.song_set.all %}
                                <div class="custom-list--item">
                                    <div class="text-dark custom-card--inline">

                                            <div class="custom-card--inline-img">
                                                <img src="{{ song.thumbnail.url }}" alt="" class="card-img--radius-sm">
                                            </div>
                                            <div class="custom-card--inline-desc">
                                                <a href="{{ song.get_absolute_url }}">
                                                    <p class="text-truncate mb-0">{{ song.title }}</p>
                                                 </a>
                                            </div>

                                    </div>
                                    <ul class="custom-card--labels d-flex ml-auto">
                                        <li>{{ song.duration }}</li>
                                        {% include 'includes/dropdown.html' %}
                                    </ul>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="tab-pane fade show" id="bio" role="tabpanel" aria-labelledby="bio-tab">
                        {% if artist.biography  %}
                            {{ artist.biography }}
                        {% else %}
                            <p>no has biography</p>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        {% include 'includes/footer.html' %}
    </main>

{% endblock %}

myalbums/templates/myalbums/artist_list.html
{% extends '../layouts/base_generic.html' %}
{% load static %}

{% block content %}

    <main id="pageWrapper">
        <div class="banner bg-song"></div>
        <div class="main-container">
            <div class="section row">
                {% for artist in artist_list %}
                    <div class="col-xl-3 col-lg-4 col-sm-6 pb-4">
                        <div class="custom-card">
                            <div class="custom-card--img">
                                <a href="{{ artist.get_absolute_url }}">
                                    <img src="{% static 'images/artists/default.jpg' %}" alt="Artist" class="card-img--radius-md" style="filter: blur(4px)">
                                    <span class="bg-blur">{{ artist.name_artist }}</span>
                                </a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
        {% include 'includes/footer.html' %}
    </main>

{% endblock %}

myalbums/templates/myalbums/category_detail.html
{% extends '../layouts/base_generic.html' %}

{% load static %}

{% block content %}

    <main id="pageWrapper">
        <div class="banner bg-song"></div>
        <div class="main-container">
            <div class="row align-items-end">
                <div class="col-6 ml-auto">
                    <form action="#" class="form-inline justify-content-end">
                        <label class="mr-2" for="filter2">Sorted By:</label>
                        <select class="custom-select mr-sm-2" id="filter2">
                            <option selected="selected">Popular</option>
                            <option value="1">A-Z</option>
                            <option value="2">Z-A</option>
                        </select>
                    </form>
                </div>
                <div class="col-12">
                    <hr>
                </div>
            </div>
            <div class="row section">
                {% if category.song_set.all.count > 0 %}
                    {% for song in category.song_set.all %}
                        <div class="col-xl-3 col-lg-4 col-sm-6 pb-4">
                            <div class="custom-card">
                                <div class="custom-card--img">
                                    <div class="custom-card--info">
                                        <div class="dropdown dropdown-icon">
                                            <a href="javascript:void(0);" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                <i class="ion-md-more"></i>
                                            </a>
                                            <ul class="dropdown-menu dropdown-menu-right">
                                                <li class="dropdown-item">
                                                    <a href="javascript:void(0);" class="dropdown-link favorite">
                                                        <i class="la la-heart-o"></i>
                                                    </a>
                                                </li>
                                                <li class="dropdown-item">
                                                    <a href="javascript:void(0);" class="dropdown-link">
                                                        <i class="la la-plus"></i>
                                                    </a>
                                                </li>
                                                <li class="dropdown-item">
                                                    <a href="javascript:void(0);" class="dropdown-link">
                                                        <i class="la la-download"></i>
                                                    </a>
                                                </li>
                                                <li class="dropdown-item">
                                                    <a href="javascript:void(0);" class="dropdown-link">
                                                        <i class="la la-share-alt"></i>
                                                    </a>
                                                </li>
                                            </ul>
                                        </div>
                                    </div>
                                    <a href="{{ song.get_absolute_url }}">
                                        {% if song.thumbnail.url %}
                                            <img src="{{song.thumbnail.url}}" style="width: 350px; height: 280px" class="card-img--radius-lg">
                                        {% else %}
                                            <img src="{% static 'images/genre/default.jpeg' %}" style="width: 350px; height: 280px" class="card-img--radius-lg">
                                        {% endif %}
                                    </a>
                                </div>
                                <a href="{{ song.get_absolute_url }}" class="custom-card--link mt-2">
                                    <h6>{{ song.title }}</h6>
                                    <p>{{ song.artist.all|join:"," }}</p>
                                    <!-- <p>{{ song.album.all|join:"," }}</p> -->
                                </a>
                            </div>
                        </div>
                    {% endfor %}
                {% else %}
                    <h3>No song found with this genre!</h3>
                {% endif %}

            </div>
        </div>
        {% include 'includes/footer.html' %}
    </main>

{% endblock %}

myalbums/templates/myalbums/category_list.html
{% extends '../layouts/base_generic.html' %}
{% load static %}

{% block content %}

    <main id="pageWrapper">

        <div class="banner bg-song"></div>
        <div class="main-container">
            <h1>Category</h1><br><br>
            <div class="section row">
            {% if category_list %}
                {% for category in category_list %}
                    <div class="col-xl-3 col-lg-4 col-sm-6 pb-4">
                        <div class="custom-card">
                            <div class="custom-card--img" style="margin-bottom: 70px;">
                                <a href="{{ category.get_absolute_url }}">
                                    <span class="bg-blur card-img--radius-md">{{ category.name_category }}</span>
                                </a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
            {% else %}
                <h4>No artist</h4>
            {% endif %}
        </div>
        {% include 'includes/footer.html' %}
    </main>

{% endblock %}

myalbums/templates/myalbums/comments.html
  <div class="custom-list--item">
    <div class="text-dark custom-card--inline">

            <div class="custom-card--inline-img">
                <img src="{{ comment.user.profile.image.url }}" alt="" class="card-img--radius-sm" style="border-radius: 50%;">

            </div>
             <div style="margin-left:10px;">
                <strong >{{ comment.user.email}}</strong>
                <p>{{ comment.date_comment }}</p>
            </div>
            <div class="custom-card--inline-desc" style="margin-left:32px;margin-top:8px;">
                   
                    <p class="text-truncate mb-0">{{ comment.text  }}</p>
                    <hr>
            </div>

    </div>

</div>